<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>as</string>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>MOS 6502 Assembly Language (ASM6)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;[^
]*
</string>
			<key>name</key>
			<string>comment.line.semicolon.mos6502</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.equate.mos6502</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.equate.mos6502</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*([a-zA-Z0-9_][a-zA-Z0-9_\.]*)([ 	]*=|[ 	]+equ[ 	]+)</string>
			<key>name</key>
			<string>meta.equate.mos6502</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.macro.directive.mos6502</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.macro.name.mos6502</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(macro)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>meta.macro.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@[a-zA-Z_][a-zA-Z0-9_]*\:?)</string>
			<key>name</key>
			<string>variable.other.local.label.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_][a-zA-Z0-9_]*\:)</string>
			<key>name</key>
			<string>support.type.label.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])\$[0-9A-Fa-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])%[01]+\b</string>
			<key>name</key>
			<string>constant.numeric.binary.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])[+-]?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.mos6502</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.interpolated.immediate.operand.mos6502</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)#([^\s]+)\b</string>
			<key>name</key>
			<string>string.interpolated.immediate.operand.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|\+|-|,|~|!|&lt;|&gt;|\*|/|%|&lt;&lt;|&gt;&gt;|&lt;&gt;|&lt;|&gt;|&lt;=|&gt;=|==|=|!=|&amp;&amp;|\|\||\^|&amp;|\|)</string>
			<key>name</key>
			<string>keyword.operator.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(x|y)\b</string>
			<key>name</key>
			<string>keyword.other.register.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.?(db|dw|byte|word|dc\.?b|dc\.?w|ds\.?b|ds\.?w|include|incbin|dl|dh|hex|pad|org|align|fillvalue|base|if|elseif|else|endif|ifdef|ifndef|endm|rept|endr|enum|ende|error)\b</string>
			<key>name</key>
			<string>support.function.directive.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(adc|and|asl|bcc|blt|bcs|bge|beq|bit|bmi|bne|bpl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|jmp|jsr|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|rti|rts|sbc|sec|sed|sei|sta|stx|sty|tax|tay|tsx|txa|txs|tya)\b</string>
			<key>name</key>
			<string>keyword.other.mnemonic.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(alr|anc|arr|axs|lax|sax|dcp|isc|rla|rra|slo|sre|skb|ign|xaa|ahx|shx|shy|tas|las)\b</string>
			<key>name</key>
			<string>invalid.illegal.mnemonic.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-z_][a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>meta.macro.or.label.usage.mos6502</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([A-Z][a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>variable.other.mos6502</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.syntax_name</string>
	<key>uuid</key>
	<string>f2b92337-0a7e-4d0f-a315-ac5ea9758428</string>
</dict>
</plist>
